services:

  labby-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labby-frontend
    ports:
      - "80:80"
    depends_on:
      - labby-backend
    restart: unless-stopped

  labby-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: labby-backend
    environment:
      - DATA_DIR=/data
      - AUTH_ENABLED=false
      - AUTH_USER_HEADER=x-auth-request-user
      - AUTH_ALLOWED_USERS=
    volumes:
      - labby-data:/data
    restart: unless-stopped

volumes:
  labby-data:
    driver: local
